project_id = "mlmsspybcqfdygcmxmjt"

[functions.transform-image]
verify_jwt = false

[functions.initialize-payment]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.webauthn-register]
verify_jwt = false

[functions.webauthn-authenticate]
verify_jwt = false